# Generated by Django 5.0.14 on 2025-05-20 16:22

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/default.jpg",
                upload_to=store.models.product_image_upload_path,
            ),
        ),
    ]
